### PR TITLE
Feature: code quality client

### PR DESCRIPTION
**Pull request by jankapunkt**
This adds the following features to the **client side of the project**:

- [x] prettier as code formatter
- [x] eslint as linter
- [x] github actions to enforce both for any pull request or push
- [x] updated developer docs

additionally, all code is

- [x] formatted
- [x] passing the linter

### CODE REVIEW

**Comment by jankapunkt** [comment]
@alessandrobelli I finally managed to fix all linter issues. However since we have no tests yet we need to carefully check, whether things still work as expected.

From what I see it's urgent to setup tests as a next step.

**Review by alessandrobelli — CHANGES_REQUESTED** [review]
There's a new error in the preparation page. To recreate, click on "new file", the new file is not shown. 
I tested the main branch and the error is not there.

**Comment by jankapunkt** [comment]
Thanks for the hint @alessandrobelli this was a negative side effect because before, it worked but it was mutating props [which we should not do](https://stackoverflow.com/a/74496033/3098783) and the linter errors on that. I have to rewrite the comoponents to work but not mutate props.

**Review by alessandrobelli — APPROVED** [review]
Quickly tested offline and it worked

**Pull request merged**
